repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ["--config-file", "pyproject.toml", "."]
        types_or: [python]
        verbose: true
        pass_filenames: false
      - id: ruff-check
        name: ruff-check
        entry: ruff check --force-exclude
        language: system
        types_or: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python]
