repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ["--config-file", "pyproject.toml", "."]
        types_or: [python]
        verbose: true
        pass_filenames: false
        stages: ["pre-push"]
      - id: ruff-check
        name: ruff-check
        entry: ruff check --force-exclude
        language: system
        types_or: [python]
        stages: ["pre-commit"]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python]
        stages: ["pre-commit"]
      - id: validate-commit-msg
        name: validate-commit-msg
        entry: .pre-commit/validate_commit_msg.py
        language: system
        stages: [commit-msg]
