repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ["--config-file", "pyproject.toml", "."]
        types_or: [python]
        verbose: true
        pass_filenames: false
        stages: ["pre-push"]
      - id: ruff-check
        name: ruff-check
        entry: ruff check --force-exclude
        language: system
        types_or: [python]
        stages: ["pre-commit"]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: system
        types_or: [python]
        stages: ["pre-commit"]
      - id: commit-msg
        name: conventional commit messages
        language: pygrep
        entry: '^(build|ci|chore|test|feat|fix|build|docs|perf|refactor|revert|style|test)!?(\([a-z]+\))?: (?![A-Z])(?![a-z]+(ed|ing)\s).*$'
        args: ["--multiline", "--negate"]
        stages: ["commit-msg"]

