project:
  type: website
  pre-render: docs/version_config.py
  output-dir: _site
  resources:
    - objects.txt
    - objects.json
  preview:
    port: 4200

metadata-files:
  - docs/reference/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  autolink: true
  aliases:
    seapig: null
    "seapig.scores": null
    "lightning.pytorch.core" : null
  sources:
    python:
      url: https://docs.python.org/3/
    torch:
      url: https://docs.pytorch.org/docs/stable/
    pathlib:
      url: https://pathlib.readthedocs.io/en/pep428/
    lightning:
      url: https://lightning.ai/docs/pytorch/stable/

format:
  html:
    theme: docs/assets/theme.scss
    css:
      - docs/assets/style.css

website:
  title: seapig
  description: Confidence based selection of compatible inputs
  repo-url: https://github.com/goergen95/seapig
  page-navigation: true
  favicon: docs/assets/logo.png
  bread-crumbs: true
  navbar:
    background: "#003661"
    pinned: true
    logo: docs/assets/logo.png
    logo-alt: seapig-home
    search: true
    left:
      - text: Reference
        file: docs/reference/index.qmd
      - text: Changelog
        file: NEWS.md
    right:
      - icon: github
        href: https://github.com/goergen95/seapig
        aria-label: seapig python GitHub
        
quartodoc:
  package: seapig
  style: pkgdown
  parser: numpy
  title: "seapig:v{{< env VERSION >}}"
  dir: docs/reference
  render_interlinks: true
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
    display_name: relative
  sidebar: docs/reference/_sidebar.yml
  sections:
    - title: Selective Inference
      desc: ""
      contents:
        - name: SelectiveInferenceTask
          members:
            - forward
            - test_step
            - predict_step
        - name: SelectiveMetric
          members:
            - update
            - compute
            - reset
    - title: Random Confidence Score
      desc: ""
      contents:
        - name: scores.RandomScore
          members:
            - score
            - select
            - set_threshold
    - title: Embedding-based Scores
      desc: ""
      contents:
        - name: scores.EuclideanScore
          members:
            - fit
            - score
            - select
            - set_threshold
        - name: scores.CosineScore
          members:
            - fit
            - score
            - select
            - set_threshold
        - name: scores.MahalanobisScore
          members:
            - fit
            - score
            - select
            - set_threshold
        - name: scores.PyODScore
          members: 
            - fit
            - score
            - select
            - set_threshold
        - name: scores.PCAScore
          members: 
            - fit
            - score
            - select
            - set_threshold
    - title: Logit-based Scores
      desc: ""
      contents:
        - name: scores.SoftmaxScore
          members:
            - score
            - select
            - set_threshold
        - name: scores.MarginScore
          members:
            - score
            - select
            - set_threshold
        - name: scores.EntropyScore
          members:
              - score
              - select
              - set_threshold
        - name: scores.EnergyScore
          members:
              - score
              - select
              - set_threshold
    - title: Abstract Base Classes
      desc: ""
      contents:
        - name: scores.ConfidenceScore
        - name: scores.EmbeddingScore
          include_inherited: true
        - name: scores.KNNScore
          include_inherited: true
        - name: scores.LogitScore
          include_inherited: true