name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

   steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: |
            requirements/**/*.txt
            **/pyproject.toml

      - name: Install dependencies
        run: uv pip install .[all]

      - name: Run tests
        run: |
          pytest --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
